FROM raspbian/jessie

# Memory limit is in Megs
ENV AB_ENABLED=jmx_exporter \
    QUARKUS_HTTP_PORT=8080 \
    MEMORY_LIMIT=128 \
    AUTODEPLOY_FOLDER=/deployments

EXPOSE ${QUARKUS_HTTP_PORT}
VOLUME ["/data"]

HEALTHCHECK --interval=15s --timeout=2s \
 CMD curl --fail http://localhost:${QUARKUS_HTTP_PORT} || exit 1

RUN apt update && apt -y install openjdk-7-jre-headless
RUN adduser --force-badname --no-create-home --disabled-password u1001 && \
    adduser u1001 root && \
    mkdir -p ${AUTODEPLOY_FOLDER} && \
    chown -R u1001 ${AUTODEPLOY_FOLDER} && \
    chmod -R "g+rwX" ${AUTODEPLOY_FOLDER} && \
    chown -R u1001:root ${AUTODEPLOY_FOLDER} && \
    mkdir -p /data

COPY target/lib/* ${AUTODEPLOY_FOLDER}/lib/
COPY target/*-runner.jar ${AUTODEPLOY_FOLDER}/app.jar

WORKDIR ${AUTODEPLOY_FOLDER}
ENTRYPOINT [ "sh", "-c", "exec java -Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=${QUARKUS_HTTP_PORT} -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xms32m -Xmx${MEMORY_LIMIT}m -jar app.jar" ]
